---
title: "Milestone 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Milestone Two, Sophia Gustafson    
               The first project that I will analyze is the "Harvard Housing" 
       Project.This project collected its own data to analyze the make-up of the 
       different Harvard Housing Blocs based off of several characteristics, and
       they collected the data through surveys and data scraping of rosters. 
       They took the time to collect their own data as opposed to using 
       that which the Crimson tabulates, to be more confident in the validity 
       of the data and to be able to have some more nuanced categories 
       (such as Middle Eastern being recorded as an ethnicity). Some of the pros
       of this project seem to be that the students could say with certainty 
       who their results represented because they collected their own data. 
       Also, having data for each house allowed for data sets that were very 
       easy to compare and understand side- by- side, as well as data that 
       was very straight forward in easy- to - read graphs. A possible con 
       is the fact that the data could be considered by some to be low-stakes. 
       It definitely does a great job dispelling Harvard myths about different 
       houses, but the data cannot be employed effectively to help a larger 
       audience. 
             The second project I will look at is Lindsey Greenhill's "Human 
       Trafficking" project. Lindsey used data that was collected by an outside 
       organization, although it does not seem that it had been widely analyzed 
       before. Her sample was not representative of all human trafficking 
       globally, but rather of the most reliable data available to analyze 
       characteristics of trafficking victims. Some pros of her project are that
       the data is very high stakes and can be used to explain a very important 
       problem to others. Also, the many differing variables which she collected
       could be displayed in very interesting ways, such as the circular ribbon 
       plot of victim movement. One possible con is that with this increased 
       amount of variables (ie. country, age, destination, type of exploitation)
       as opposed to the straightforward nature of the other project (comparing 
       characteristics to each house), there is so much data that the 
       comparisons could in a sense be endless. This leaves many questions 
       answered, but many unanswered as well which is a tough characteristic 
       of a project. 
